name: Unit Test / Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn type
      - name: Unit Test
        run: yarn test --coverage
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
          flags: unittest
          name: codecov-umbrella
          fail_ci_if_error: true
